// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPumpByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPumpByIdRequest) Reset()         { *m = GetPumpByIdRequest{} }
func (m *GetPumpByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetPumpByIdRequest) ProtoMessage()    {}
func (*GetPumpByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *GetPumpByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPumpByIdRequest.Unmarshal(m, b)
}
func (m *GetPumpByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPumpByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetPumpByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPumpByIdRequest.Merge(m, src)
}
func (m *GetPumpByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetPumpByIdRequest.Size(m)
}
func (m *GetPumpByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPumpByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPumpByIdRequest proto.InternalMessageInfo

func (m *GetPumpByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPumpByIdResponse struct {
	Pump                 *Pump    `protobuf:"bytes,1,opt,name=pump,proto3" json:"pump,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPumpByIdResponse) Reset()         { *m = GetPumpByIdResponse{} }
func (m *GetPumpByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetPumpByIdResponse) ProtoMessage()    {}
func (*GetPumpByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *GetPumpByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPumpByIdResponse.Unmarshal(m, b)
}
func (m *GetPumpByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPumpByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetPumpByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPumpByIdResponse.Merge(m, src)
}
func (m *GetPumpByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetPumpByIdResponse.Size(m)
}
func (m *GetPumpByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPumpByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPumpByIdResponse proto.InternalMessageInfo

func (m *GetPumpByIdResponse) GetPump() *Pump {
	if m != nil {
		return m.Pump
	}
	return nil
}

type ListPumpsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPumpsRequest) Reset()         { *m = ListPumpsRequest{} }
func (m *ListPumpsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPumpsRequest) ProtoMessage()    {}
func (*ListPumpsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ListPumpsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPumpsRequest.Unmarshal(m, b)
}
func (m *ListPumpsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPumpsRequest.Marshal(b, m, deterministic)
}
func (m *ListPumpsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPumpsRequest.Merge(m, src)
}
func (m *ListPumpsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPumpsRequest.Size(m)
}
func (m *ListPumpsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPumpsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPumpsRequest proto.InternalMessageInfo

type ListPumpsResponse struct {
	Pumps                []*Pump  `protobuf:"bytes,1,rep,name=pumps,proto3" json:"pumps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPumpsResponse) Reset()         { *m = ListPumpsResponse{} }
func (m *ListPumpsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPumpsResponse) ProtoMessage()    {}
func (*ListPumpsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *ListPumpsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPumpsResponse.Unmarshal(m, b)
}
func (m *ListPumpsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPumpsResponse.Marshal(b, m, deterministic)
}
func (m *ListPumpsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPumpsResponse.Merge(m, src)
}
func (m *ListPumpsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPumpsResponse.Size(m)
}
func (m *ListPumpsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPumpsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPumpsResponse proto.InternalMessageInfo

func (m *ListPumpsResponse) GetPumps() []*Pump {
	if m != nil {
		return m.Pumps
	}
	return nil
}

type Pump struct {
	// unique device identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// device display name
	DisplayName string `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	// device manufacturers
	Manufacturers []string `protobuf:"bytes,3,rep,name=manufacturers,proto3" json:"manufacturers,omitempty"`
	// device model
	Model                string   `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pump) Reset()         { *m = Pump{} }
func (m *Pump) String() string { return proto.CompactTextString(m) }
func (*Pump) ProtoMessage()    {}
func (*Pump) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *Pump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pump.Unmarshal(m, b)
}
func (m *Pump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pump.Marshal(b, m, deterministic)
}
func (m *Pump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pump.Merge(m, src)
}
func (m *Pump) XXX_Size() int {
	return xxx_messageInfo_Pump.Size(m)
}
func (m *Pump) XXX_DiscardUnknown() {
	xxx_messageInfo_Pump.DiscardUnknown(m)
}

var xxx_messageInfo_Pump proto.InternalMessageInfo

func (m *Pump) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pump) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Pump) GetManufacturers() []string {
	if m != nil {
		return m.Manufacturers
	}
	return nil
}

func (m *Pump) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

type GetCgmByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCgmByIdRequest) Reset()         { *m = GetCgmByIdRequest{} }
func (m *GetCgmByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetCgmByIdRequest) ProtoMessage()    {}
func (*GetCgmByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetCgmByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCgmByIdRequest.Unmarshal(m, b)
}
func (m *GetCgmByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCgmByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetCgmByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCgmByIdRequest.Merge(m, src)
}
func (m *GetCgmByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetCgmByIdRequest.Size(m)
}
func (m *GetCgmByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCgmByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCgmByIdRequest proto.InternalMessageInfo

func (m *GetCgmByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetCgmByIdResponse struct {
	Cgm                  *Cgm     `protobuf:"bytes,1,opt,name=cgm,proto3" json:"cgm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCgmByIdResponse) Reset()         { *m = GetCgmByIdResponse{} }
func (m *GetCgmByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetCgmByIdResponse) ProtoMessage()    {}
func (*GetCgmByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *GetCgmByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCgmByIdResponse.Unmarshal(m, b)
}
func (m *GetCgmByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCgmByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetCgmByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCgmByIdResponse.Merge(m, src)
}
func (m *GetCgmByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetCgmByIdResponse.Size(m)
}
func (m *GetCgmByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCgmByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCgmByIdResponse proto.InternalMessageInfo

func (m *GetCgmByIdResponse) GetCgm() *Cgm {
	if m != nil {
		return m.Cgm
	}
	return nil
}

type ListCgmsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCgmsRequest) Reset()         { *m = ListCgmsRequest{} }
func (m *ListCgmsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCgmsRequest) ProtoMessage()    {}
func (*ListCgmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *ListCgmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCgmsRequest.Unmarshal(m, b)
}
func (m *ListCgmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCgmsRequest.Marshal(b, m, deterministic)
}
func (m *ListCgmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCgmsRequest.Merge(m, src)
}
func (m *ListCgmsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCgmsRequest.Size(m)
}
func (m *ListCgmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCgmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCgmsRequest proto.InternalMessageInfo

type ListCgmsResponse struct {
	Cgms                 []*Cgm   `protobuf:"bytes,1,rep,name=cgms,proto3" json:"cgms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCgmsResponse) Reset()         { *m = ListCgmsResponse{} }
func (m *ListCgmsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCgmsResponse) ProtoMessage()    {}
func (*ListCgmsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *ListCgmsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCgmsResponse.Unmarshal(m, b)
}
func (m *ListCgmsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCgmsResponse.Marshal(b, m, deterministic)
}
func (m *ListCgmsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCgmsResponse.Merge(m, src)
}
func (m *ListCgmsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCgmsResponse.Size(m)
}
func (m *ListCgmsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCgmsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCgmsResponse proto.InternalMessageInfo

func (m *ListCgmsResponse) GetCgms() []*Cgm {
	if m != nil {
		return m.Cgms
	}
	return nil
}

type Cgm struct {
	// unique device identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// device display name
	DisplayName string `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	// device manufacturers
	Manufacturers []string `protobuf:"bytes,3,rep,name=manufacturers,proto3" json:"manufacturers,omitempty"`
	// device model
	Model                string   `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cgm) Reset()         { *m = Cgm{} }
func (m *Cgm) String() string { return proto.CompactTextString(m) }
func (*Cgm) ProtoMessage()    {}
func (*Cgm) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *Cgm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cgm.Unmarshal(m, b)
}
func (m *Cgm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cgm.Marshal(b, m, deterministic)
}
func (m *Cgm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cgm.Merge(m, src)
}
func (m *Cgm) XXX_Size() int {
	return xxx_messageInfo_Cgm.Size(m)
}
func (m *Cgm) XXX_DiscardUnknown() {
	xxx_messageInfo_Cgm.DiscardUnknown(m)
}

var xxx_messageInfo_Cgm proto.InternalMessageInfo

func (m *Cgm) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cgm) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Cgm) GetManufacturers() []string {
	if m != nil {
		return m.Manufacturers
	}
	return nil
}

func (m *Cgm) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPumpByIdRequest)(nil), "api.GetPumpByIdRequest")
	proto.RegisterType((*GetPumpByIdResponse)(nil), "api.GetPumpByIdResponse")
	proto.RegisterType((*ListPumpsRequest)(nil), "api.ListPumpsRequest")
	proto.RegisterType((*ListPumpsResponse)(nil), "api.ListPumpsResponse")
	proto.RegisterType((*Pump)(nil), "api.Pump")
	proto.RegisterType((*GetCgmByIdRequest)(nil), "api.GetCgmByIdRequest")
	proto.RegisterType((*GetCgmByIdResponse)(nil), "api.GetCgmByIdResponse")
	proto.RegisterType((*ListCgmsRequest)(nil), "api.ListCgmsRequest")
	proto.RegisterType((*ListCgmsResponse)(nil), "api.ListCgmsResponse")
	proto.RegisterType((*Cgm)(nil), "api.Cgm")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x5d, 0xcb, 0xd3, 0x30,
	0x14, 0xc7, 0x5d, 0xdb, 0x47, 0x9f, 0x9e, 0xe1, 0xcb, 0xe2, 0x5e, 0x4a, 0x51, 0x2c, 0xd9, 0x84,
	0xdd, 0xb8, 0x8d, 0xb9, 0x1b, 0x41, 0x10, 0x56, 0x61, 0x08, 0x22, 0xd2, 0x4b, 0xef, 0xba, 0x36,
	0xc6, 0xc0, 0xb2, 0xc4, 0x26, 0x15, 0xf6, 0x09, 0xfc, 0xda, 0xd2, 0xf4, 0x65, 0x6d, 0x07, 0x5e,
	0x3e, 0x97, 0xfd, 0xe5, 0x9c, 0x7f, 0x92, 0x5f, 0x4e, 0xc1, 0x8d, 0x25, 0x5b, 0xc9, 0x4c, 0x68,
	0x81, 0xec, 0x58, 0x32, 0xbc, 0x00, 0x74, 0x20, 0xfa, 0x7b, 0xce, 0xe5, 0xfe, 0xf2, 0x25, 0x8d,
	0xc8, 0xef, 0x9c, 0x28, 0x8d, 0x9e, 0x81, 0xc5, 0x52, 0x6f, 0x10, 0x0c, 0x96, 0x6e, 0x64, 0xb1,
	0x14, 0xef, 0xe0, 0x65, 0xa7, 0x4a, 0x49, 0x71, 0x56, 0x04, 0xbd, 0x06, 0x47, 0xe6, 0x5c, 0x9a,
	0xc2, 0xe1, 0xd6, 0x5d, 0x15, 0xd9, 0x45, 0x51, 0x64, 0x30, 0x46, 0xf0, 0xe2, 0x2b, 0x53, 0xa6,
	0x4d, 0x55, 0xc9, 0x78, 0x07, 0xa3, 0x16, 0xab, 0x72, 0xde, 0xc0, 0x5d, 0xd1, 0xa0, 0xbc, 0x41,
	0x60, 0x77, 0x83, 0x4a, 0x8e, 0x35, 0x38, 0xc5, 0x67, 0xff, 0x5c, 0x28, 0x80, 0x61, 0xca, 0x94,
	0x3c, 0xc5, 0x97, 0x6f, 0x31, 0x27, 0x9e, 0x65, 0x16, 0xda, 0x08, 0x2d, 0xe0, 0x29, 0x8f, 0xcf,
	0xf9, 0xcf, 0x38, 0xd1, 0x79, 0x46, 0x32, 0xe5, 0xd9, 0x81, 0xbd, 0x74, 0xa3, 0x2e, 0x44, 0x63,
	0xb8, 0xe3, 0x22, 0x25, 0x27, 0xcf, 0x31, 0x09, 0xe5, 0x07, 0x9e, 0xc3, 0xe8, 0x40, 0x74, 0x48,
	0xf9, 0xff, 0xd4, 0x6c, 0x8c, 0xc0, 0xa6, 0xa8, 0xba, 0x91, 0x0f, 0x76, 0x42, 0x79, 0x25, 0xe6,
	0xde, 0xdc, 0x27, 0xa4, 0x3c, 0x2a, 0x20, 0x1e, 0xc1, 0xf3, 0x42, 0x41, 0x48, 0x79, 0x63, 0x65,
	0x53, 0x9a, 0x2a, 0x51, 0x15, 0xf1, 0x0a, 0x9c, 0x84, 0xf2, 0xda, 0xc9, 0x35, 0xc3, 0x50, 0xac,
	0xc0, 0x0e, 0x29, 0x7f, 0x58, 0x21, 0xdb, 0xbf, 0x16, 0x3c, 0xf9, 0x4c, 0xfe, 0xb0, 0x84, 0x28,
	0xb4, 0x87, 0x61, 0x6b, 0x24, 0xd0, 0xcc, 0x9c, 0xef, 0x76, 0x94, 0x7c, 0xef, 0x76, 0xa1, 0xbc,
	0x20, 0x7e, 0x84, 0x3e, 0x82, 0xdb, 0x0c, 0x03, 0x9a, 0x98, 0xc2, 0xfe, 0xc0, 0xf8, 0xd3, 0x3e,
	0x6e, 0xba, 0x3f, 0x01, 0x5c, 0xcd, 0xa3, 0x69, 0xbd, 0x4f, 0xf7, 0xbd, 0xfc, 0xd9, 0x0d, 0x6f,
	0x02, 0x3e, 0xc0, 0x7d, 0x6d, 0x1d, 0x8d, 0x9b, 0x6d, 0x5a, 0xef, 0xe2, 0x4f, 0x7a, 0xb4, 0x6e,
	0xdd, 0xbf, 0xfd, 0x31, 0xa7, 0x4c, 0xff, 0xca, 0x8f, 0xab, 0x44, 0xf0, 0xb5, 0x66, 0x29, 0x91,
	0x42, 0x9c, 0xde, 0x89, 0x8c, 0xae, 0xd3, 0x52, 0xd0, 0x3a, 0x96, 0xec, 0xf8, 0xd8, 0xfc, 0x69,
	0xef, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xb2, 0x24, 0x09, 0x76, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DevicesClient is the client API for Devices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DevicesClient interface {
	// Get pump by id
	GetPumpById(ctx context.Context, in *GetPumpByIdRequest, opts ...grpc.CallOption) (*GetPumpByIdResponse, error)
	// List pumps
	ListPumps(ctx context.Context, in *ListPumpsRequest, opts ...grpc.CallOption) (*ListPumpsResponse, error)
	// Get cgm by id
	GetCgmById(ctx context.Context, in *GetCgmByIdRequest, opts ...grpc.CallOption) (*GetCgmByIdResponse, error)
	// List cgms
	ListCgms(ctx context.Context, in *ListCgmsRequest, opts ...grpc.CallOption) (*ListCgmsResponse, error)
}

type devicesClient struct {
	cc grpc.ClientConnInterface
}

func NewDevicesClient(cc grpc.ClientConnInterface) DevicesClient {
	return &devicesClient{cc}
}

func (c *devicesClient) GetPumpById(ctx context.Context, in *GetPumpByIdRequest, opts ...grpc.CallOption) (*GetPumpByIdResponse, error) {
	out := new(GetPumpByIdResponse)
	err := c.cc.Invoke(ctx, "/api.Devices/GetPumpById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) ListPumps(ctx context.Context, in *ListPumpsRequest, opts ...grpc.CallOption) (*ListPumpsResponse, error) {
	out := new(ListPumpsResponse)
	err := c.cc.Invoke(ctx, "/api.Devices/ListPumps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) GetCgmById(ctx context.Context, in *GetCgmByIdRequest, opts ...grpc.CallOption) (*GetCgmByIdResponse, error) {
	out := new(GetCgmByIdResponse)
	err := c.cc.Invoke(ctx, "/api.Devices/GetCgmById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) ListCgms(ctx context.Context, in *ListCgmsRequest, opts ...grpc.CallOption) (*ListCgmsResponse, error) {
	out := new(ListCgmsResponse)
	err := c.cc.Invoke(ctx, "/api.Devices/ListCgms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevicesServer is the server API for Devices service.
type DevicesServer interface {
	// Get pump by id
	GetPumpById(context.Context, *GetPumpByIdRequest) (*GetPumpByIdResponse, error)
	// List pumps
	ListPumps(context.Context, *ListPumpsRequest) (*ListPumpsResponse, error)
	// Get cgm by id
	GetCgmById(context.Context, *GetCgmByIdRequest) (*GetCgmByIdResponse, error)
	// List cgms
	ListCgms(context.Context, *ListCgmsRequest) (*ListCgmsResponse, error)
}

// UnimplementedDevicesServer can be embedded to have forward compatible implementations.
type UnimplementedDevicesServer struct {
}

func (*UnimplementedDevicesServer) GetPumpById(ctx context.Context, req *GetPumpByIdRequest) (*GetPumpByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPumpById not implemented")
}
func (*UnimplementedDevicesServer) ListPumps(ctx context.Context, req *ListPumpsRequest) (*ListPumpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPumps not implemented")
}
func (*UnimplementedDevicesServer) GetCgmById(ctx context.Context, req *GetCgmByIdRequest) (*GetCgmByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCgmById not implemented")
}
func (*UnimplementedDevicesServer) ListCgms(ctx context.Context, req *ListCgmsRequest) (*ListCgmsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCgms not implemented")
}

func RegisterDevicesServer(s *grpc.Server, srv DevicesServer) {
	s.RegisterService(&_Devices_serviceDesc, srv)
}

func _Devices_GetPumpById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPumpByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).GetPumpById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Devices/GetPumpById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).GetPumpById(ctx, req.(*GetPumpByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_ListPumps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPumpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).ListPumps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Devices/ListPumps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).ListPumps(ctx, req.(*ListPumpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_GetCgmById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCgmByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).GetCgmById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Devices/GetCgmById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).GetCgmById(ctx, req.(*GetCgmByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_ListCgms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCgmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).ListCgms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Devices/ListCgms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).ListCgms(ctx, req.(*ListCgmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Devices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Devices",
	HandlerType: (*DevicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPumpById",
			Handler:    _Devices_GetPumpById_Handler,
		},
		{
			MethodName: "ListPumps",
			Handler:    _Devices_ListPumps_Handler,
		},
		{
			MethodName: "GetCgmById",
			Handler:    _Devices_GetCgmById_Handler,
		},
		{
			MethodName: "ListCgms",
			Handler:    _Devices_ListCgms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
